routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/exams', 'ExamController');

Route::resource('/users', 'UserController');

Route::get('/doExam/{id}', 'ExamController@doExam')->name('doExam');

Route::resource('/subjects', 'SubjectCodeController');

Route::resource('/questions', 'QuestionController');

Route::get('/importQuestionForm', 'ExamController@importQuestionForm')->name('importQuestionForm');

Route::get('/importCalculateGradeForm', function(){
    return view('importCalculateGrade');
})->name('importCalculateGradeForm');

Route::post('/importQuestionExcel', 'ExamController@importQuestionExcel')->name('importQuestionExcel');

Route::post('/importCalculateGradeExcel', 'ExamController@importCalculateGradeForm')->name('importCalculateGradeExcel');

Route::post('/submitExam', 'ExamController@submitExam')->name('submitExam');

Route::get('admin', function(){
    return view('admin-area');
})->name('admin-area');

Route::get('highScore', 'ExamController@highScore')->name('highScore');

Route::get('question/remove/attachment/{id}', 'QuestionController@removeAttachment')->name('remove_attachment');

Route::get('addUser', 'UserController@create')->name('addUser');

resources/views/addUser.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if (\Session::has('error'))
                    <div class="alert alert-danger">
                        <ul>
                            <li>{!! \Session::get('error') !!}</li>
                        </ul>
                    </div>
                @endif

                @if (\Session::has('msg'))
                    <div class="alert alert-success">
                        <ul>
                            <li>{!! \Session::get('msg') !!}</li>
                        </ul>
                    </div>
                @endif
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <h1 class="w-100">Add User</h1>
                <p>
                    <a href="{{ route('users.index') }}" class="btn btn-success">Go back List User</a>
                </p>
            </div>
        </div>

        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Add User') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('users.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}" autocomplete="off" autofocus>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" autocomplete="off">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control " name="password" autocomplete="off">
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Add User') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin-area.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row text-center">
            <div class="col-12">
                <span class="text-center">Admin Area</span>
            </div>
        </div>
    </div>
@endsection

resources/views/editQuestion.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            <h1>Edit Question</h1>
        </div>
		<div class="row">
            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">

            <form action="{{ route('questions.update', ['question' => $question->id]) }}" enctype="multipart/form-data" method="POST" class="w-100">
                @csrf
                @method('PUT')
				@if ($errors->any())

					<div class="alert alert-danger">

						<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

						<ul>

							@foreach ($errors->all() as $error)

								<li>{{ $error }}</li>

							@endforeach

						</ul>

					</div>

				@endif



				@if (Session::has('success'))

					<div class="alert alert-success">

						<a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

						<p>{{ Session::get('success') }}</p>

					</div>

				@endif
                <div class="form-group">
                    <label for="the_questions">The question</label>
                    <input type="text" class="form-control" id="the_question" name="the_question" value="{{ $question->the_question }}">
                </div>

                <div class="form-group">
                    <label for="correct_answer">Correct Answer</label>
                    <input type="text" class="form-control" id="correct_answer" name="correct_answer" value="{{ $question->correct_answer }}">
                    <small>
                        A: 1; B: 2; C: 3; D: 4;
                    </small>
                </div>

                <div class="form-group">
                    <label for="answer_1">Answer 1</label>
                    <input type="text" class="form-control" id="answer_1" name="answer_1" value="{{ $question->answer_1 }}">
                </div>

                <div class="form-group">
                    <label for="answer_2">Answer 2</label>
                    <input type="text" class="form-control" id="answer_2" name="answer_2" value="{{ $question->answer_2 }}">
                </div>

                <div class="form-group">
                    <label for="answer_3">Answer 3</label>
                    <input type="text" class="form-control" id="answer_3" name="answer_3" value="{{ $question->answer_3 }}">
                </div>

                <div class="form-group">
                    <label for="answer_4">Answer 4</label>
                    <input type="text" class="form-control" id="answer_4" name="answer_4" value="{{ $question->answer_4 }}">
                </div>

                <div class="form-group">
                    <small>Part {{ $question->part->part }}</small>
                </div>

                <div class="form-group">
                    <label for="attachment">Attachment</label>
                    <input type="file" class="form-control-file" id="attachment" name="attachment">
                    <small>Current file: {{ $question->attachment != '' ? $question->attachment : 'No attachment' }}</small>
                    @if ($question->attachment)
                    <p><a href="{{ route('remove_attachment', ['id' => $question->id]) }}" class="btn btn-danger">Remove Image</a></p>
                    @endif
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/editSubjectCode.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            <h1>Edit Subject</h1>
        </div>
        <div class="row">
            <a href="{{ route('subjects.index') }}" class="btn btn-primary  ">Go to list Subject</a>
        </div>
        <div class="row">
            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">

            <form action="{{ route('subjects.update', ['subject' => $subject->id]) }}" method="POST" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ $subject->title }}">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" cols="30" rows="5" class="form-control">{{ $subject->description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="listening_file">Listening file</label>
                    <input type="file" class="form-control-file" id="listening_file" name="listening_file">
                    <small>Current file: {{ $subject->listening_file }}</small>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
@endsection

resources/views/editUser.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            <h1>Edit User</h1>
        </div>
        <div class="row">
            <a href="{{ route('users.index') }}" class="btn btn-primary  ">Go to list users</a>
        </div>
        <div class="row">
            @if (\Session::has('error'))
                <div class="alert alert-danger">
                    <ul>
                        <li>{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif

            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <form action="{{ route('users.update', ['subject' => $user->id]) }}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="name">Name</label>
                    <input type="text" class="form-control" id="name" name="name" value="{{ $user->name }}">
                </div>
                <div class="form-group">
                    <label for="role">Role</label>
                    <select name="role" id="role" class="form-control">
                        <option value="admin" {{ $user->role == 'admin' ? 'selected' : '' }}>admin</option>
                        <option value="member" {{ $user->role == 'member' ? 'selected' : '' }}>member</option>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>

@endsection

resources/views/high_score.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h1>High score (top 10)</h1>
                <table class="table">
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Listening correct - grade</th>
                        <th>Reading correct - grade</th>
                        <th>Total</th>
                        <th>Time create</th>
                    </tr>
                    <?php $count = 1 ?>
                    @foreach ($top_high_score as $high_score)
                    <tr>
                        <td>{{ $count++ }}</td>
                        <td>{{ $high_score->user->name }}</td>
                        @if ($high_score->listening_correct == 0)
                            <td>0 - 0</td>
                        @else
                            <td>{{ $high_score->listening_correct }} - {{ (\App\Grade::where('total_correct', '=', $high_score->listening_correct)->get())[0]->grade_listening }}</td>
                        @endif

                        @if ($high_score->reading_correct == 0)
                            <td>0 - 0</td>
                        @else
                            <td>{{ $high_score->reading_correct }} - {{ (\App\Grade::where('total_correct', '=', $high_score->reading_correct)->get())[0]->grade_reading }}</td>
                        @endif
                        <td>{{ $high_score->total_grade }}</td>
                        <td>{{ $high_score->created_at }}</td>
                    </tr>
                    @endforeach
                </table>
            </div>

        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    <p>Let's do the test !</p>
                    <p><a href="{{ route('exams.index') }}" class="btn btn-success">Do exam</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/importCalculateGrade.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            @if (\Session::has('error'))
                <div class="alert alert-danger">
                    <ul>
                        <li>{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif

            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="panel panel-default">

            <div class="panel-heading">

                <h1>Import Grades</h1>

            </div>

            <div class="panel-body">


                <form style="border: 4px solid #a1a1a1;margin-top: 15px;padding: 10px;" action="{{ route('importCalculateGradeExcel') }}" class="form-horizontal" method="post" enctype="multipart/form-data">

                    @csrf
                    <div class="form-group">
                        <label for="import_file">File</label>
                        <input type="file" class="form-control-file" id="import_file" name="import_file">
                    </div>

                    <button class="btn btn-primary">Import File</button>

                </form>

            </div>

        </div>

    </div>
@endsection

resources/views/importQuestion.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            @if (\Session::has('error'))
                <div class="alert alert-danger">
                    <ul>
                        <li>{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif

            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="panel panel-default">

            <div class="panel-heading">

                <h1>Import Questions</h1>

            </div>

            <div class="panel-body">


                <form style="border: 4px solid #a1a1a1;margin-top: 15px;padding: 10px;" action="{{ route('importQuestionExcel') }}" class="form-horizontal" method="post" enctype="multipart/form-data">

                    @csrf



                    @if ($errors->any())

                        <div class="alert alert-danger">

                            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

                            <ul>

                                @foreach ($errors->all() as $error)

                                    <li>{{ $error }}</li>

                                @endforeach

                            </ul>

                        </div>

                    @endif



                    @if (Session::has('success'))

                        <div class="alert alert-success">

                            <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>

                            <p>{{ Session::get('success') }}</p>

                        </div>

                    @endif

                    <label for="subject_code">Subject Code</label><br>
                    <select name="subject_code" id="subject_code" class="form-control">
                        @foreach($list_subject_code as $subject_code)
                            <option value="{{ $subject_code['id'] }}">{{ $subject_code['title'] }}</option>
                        @endforeach
                    </select>


                    <div class="form-group">
                        <label for="import_file">File</label>
                        <input type="file" class="form-control-file" id="import_file" name="import_file">
                    </div>

                    <button class="btn btn-primary">Import File</button>

                </form>



            </div>

        </div>

    </div>
@endsection

resources/views/listQuestion.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            @if (\Session::has('error'))
                <div class="alert alert-danger">
                    <ul>
                        <li>{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif

            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <h1>List questions</h1>
            <table class="table table-bordered dataTable" id="datatable_paginate">
                <thead>
                <tr>
                    <th scope="col">Subject</th>
                    <th scope="col">Question</th>
                    <th scope="col">Correct Answer</th>
                    <th scope="col">Part</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                <?php
                $text_correct_answer = ['A', 'B', 'C', 'D'];
                ?>
                @foreach($listQuestion as $question)
                    <tr>
                        <td>
                            <a href="{{ route("subjects.edit", ["id" => $question->part->subjectCode->id]) }}" target="_blank">
                                {{ $question->part->subjectCode->title }}
                            </a>
                        </td>
                        <td>
                            @if ($question->attachment)
                                <img src="{{ $question->attachment }}" style="max-width: 80px;" alt="">
                            @endif
                            {{ $question->the_question }}
                        </td>
                        <td>{{ $text_correct_answer[$question->correct_answer - 1] }}</td>
                        <td>Part {{ $question->part->part }}</td>
                        <td>
                            <a href="{{ route('questions.edit', ['questions' => $question->id]) }}">
                                <i class="fa fa-pencil"></i>
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <link rel="stylesheet" href="{{ asset('lib_admin/datatables/dataTables.bootstrap4.min.css') }}">
    <script src="{{ asset('lib_admin/datatables/jquery.dataTables.min.js') }}" defer></script>
    <script src="{{ asset('lib_admin/datatables/dataTables.bootstrap4.min.js') }}" defer></script>
    <script>
        $(document).ready(function() {
            $('#datatable_paginate').DataTable();
        });
    </script>
@endsection

resources/views/listSubjectCode.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row list-button">
            <button class="btn btn-primary show_form_add_subject_code">Add Subject</button>
        </div>
        <br>
        <div class="row form_add_subject_code">
            <form action="{{ route('subjects.store') }}" style="display: none;" enctype="multipart/form-data" class="w-100" method="POST">
                @csrf
                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea name="description" id="description" cols="30" rows="5" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="listening_file">Listening file</label>
                    <input type="file" class="form-control-file" id="listening_file" name="listening_file">
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

        <br>

        <div class="row">
            @if (\Session::has('error'))
                <div class="alert alert-danger">
                    <ul>
                        <li>{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif

            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>

        <div class="row">
            <h1>List Subjects</h1>
            <table class="table table-bordered dataTable" id="datatable_paginate">
                <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Title</th>
                    <th scope="col">Listening file</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($listSubject as $subject)
                    <tr>
                        <th scope="row">{{ $subject->id }}</th>
                        <td>{{ $subject->title }}</td>
                        <td><a href="{{ asset($subject->listening_file) }}" title="click to download">{{ $subject->listening_file }}</a></td>
                        <td>
                            <a href="{{ route('subjects.edit', ['subject' => $subject->id]) }}">
                                <i class="fa fa-pencil"></i>
                            </a>
                            <a href="javascript:void(0);" data-subject-id="{{ $subject->id }}" class="delete_subject">
                                <i class="fa fa-trash"></i>
                            </a>
                            <form action="{{ route('subjects.destroy', ['subject' => $subject->id]) }}" class="hidden form_delete_{{ $subject->id }}" method="POST">
                                @method('DELETE')
                                @csrf
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>

    </div>


    <script>

        jQuery(document).ready(function(){
            jQuery(document).on('click', '.show_form_add_subject_code', function(){
                console.log('ok');
                const form_add_subject = jQuery('.form_add_subject_code form');
                if (form_add_subject.hasClass('show_form')) {
                    form_add_subject.slideUp();
                    form_add_subject.removeClass('show_form');
                } else {
                    form_add_subject.slideDown();
                    form_add_subject.addClass('show_form');
                }

            });

            jQuery(document).on('click', '.delete_subject', function(){
                if (!confirm('Are you sure ?')) {

                    return false;
                } else {

                    let class_form_delete = '.form_delete_' + jQuery(this).attr('data-subject-id');

                    jQuery(class_form_delete).submit();
                }
            });
        });

    </script>
    <link rel="stylesheet" href="{{ asset('lib_admin/datatables/dataTables.bootstrap4.min.css') }}">
    <script src="{{ asset('lib_admin/datatables/jquery.dataTables.min.js') }}" defer></script>
    <script src="{{ asset('lib_admin/datatables/dataTables.bootstrap4.min.js') }}" defer></script>
    <script>
        $(document).ready(function() {
            $('#datatable_paginate').DataTable();
        });
    </script>
@endsection

resources/views/listUser.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container">
        <div class="row">
            @if (\Session::has('error'))
                <div class="alert alert-danger">
                    <ul>
                        <li>{!! \Session::get('error') !!}</li>
                    </ul>
                </div>
            @endif

            @if (\Session::has('msg'))
                <div class="alert alert-success">
                    <ul>
                        <li>{!! \Session::get('msg') !!}</li>
                    </ul>
                </div>
            @endif
        </div>
        <div class="row">
            <h1 class="w-100">List Users</h1>
            <p><a href="{{ route('addUser') }}" class="btn btn-success">Add User</a></p>
            <table class="table table-bordered dataTable" id="datatable_paginate">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Created at</th>
                    <th scope="col">Action</th>
                </tr>
                </thead>
                <tbody>
                @foreach($users as $user)
                    <tr>
                        <td>{{ $user->id }}</td>
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->email }}</td>
                        <td>{{ $user->created_at }}</td>
                        <td>
                            <a class="" href="{{ route('users.edit', ['users' => $user->id]) }}" style="padding-right: 10px;">
                                <i class="fa fa-pencil"></i>
                            </a>
                            @if (auth()->user()->id != $user->id)
                            <a href="javascript:void(0);" data-user-id="{{ $user->id }}" class="delete_user">
                                <i class="fa fa-trash"></i>
                            </a>
                            <form action="{{ route('users.destroy', ['user' => $user->id]) }}" class="hidden form_delete_{{ $user->id }}" method="POST">
                                @method('DELETE')
                                @csrf
                            </form>
                            @endif
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    <link rel="stylesheet" href="{{ asset('lib_admin/datatables/dataTables.bootstrap4.min.css') }}">
    <script src="{{ asset('lib_admin/datatables/jquery.dataTables.min.js') }}" defer></script>
    <script src="{{ asset('lib_admin/datatables/dataTables.bootstrap4.min.js') }}" defer></script>

    <script>
        $(document).ready(function() {
            jQuery(document).on('click', '.delete_user', function(){
                if (!confirm('Are you sure ?')) {

                    return false;
                } else {

                    let class_form_delete = '.form_delete_' + jQuery(this).attr('data-user-id');

                    jQuery(class_form_delete).submit();
                }
            });
            $('#datatable_paginate').DataTable();
        });
    </script>
@endsection